# Generated by Django 3.0.8 on 2020-11-24 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 24, 8, 14, 45, 388379, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
